
###Brook Trout Genome All Streams SamTools####

###read in covMat from using angsd with SNP list (get_beagle).


#Data

AllStreamsSamTools.cov <- as.matrix(read.table(paste0("C:/Users/cneme/Documents/PCAs/AllStreams_SamTools_GLfromSNPList.covMat"), header= F))

#I need to bring in data so I can have a population column and individual ID

#Bring in all the sample merge texts from compute canada and merge those to start

BH.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/BlackHole_samplemerge.txt", header = F)
CV.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/ChurchVault_samplemerge.txt", header = F)
HE.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/Healeys_samplemerge.txt", header = F)
PL.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/Poole_samplemerge.txt", header = F)
RB.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/Robinson_samplemerge.txt", header = F)
RC.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/RossCreek_samplemerge.txt", header = F)
SB.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/SaundersBrookDownstream_samplemerge.txt", header = F)
SS.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/SheepShearer_samplemerge.txt", header = F)
WW.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/WoodworthDownstream_samplemerge.txt", header = F)


#Add a column to each sample table to specify the population or stream name
BH.names$Population <- "Black Hole"
CV.names$Population <- "Church Vault"
HE.names$Population <- "Healeys"
PL.names$Population <- "Poole"
RB.names$Population <- "Robinson"
RC.names$Population <- "Ross Creek"
SB.names$Population <- "Saunders"
SS.names$Population <- "Sheep Shearer"
WW.names$Population <- "Woodworth"

#Add a column for geology
BH.names$geology <- "Scoured Glacial Till"
CV.names$geology <- "Thick Stony Glacial Till"
HE.names$geology <- "Silt"
PL.names$geology <- "Silt"
RB.names$geology <- "Thick Stony Glacial Till"
RC.names$geology <- "Scoured Glacial Till"
SB.names$geology <- "Thick Stony Glacial Till"
SS.names$geology <- "Silt"
WW.names$geology <- "Scoured Glacial Till"

#bind all tables
AllStreamsNames <- rbind(BH.names,CV.names,HE.names,PL.names,RB.names,RC.names,SB.names,SS.names,WW.names)


#change geology column to factor
AllStreamsNames$Population <- as.factor(AllStreamsNames$Population)
AllStreamsNames$geology <- as.factor(AllStreamsNames$geology)

PCA <- function(cov_matrix, x_axis, y_axis)
{
  ## This function takes a covariance matrix and performs PCA. 
  # cov_matrix: a square covariance matrix generated by most pca softwares
  # ind_label: a vector in the same order and length as cov_matrix; it contains the individual labels of the individuals represented in the covariance matrix
  # pop_label: a vector in the same order and length as cov_matrix; it contains the population labels of the individuals represented in the covariance matrix
  # x_axis: an integer that determines which principal component to plot on the x axis
  # y_axis: an integer that determines which principal component to plot on the y axis
  # show.point: whether to show individual points
  # show.label: whether to show population labels
  # show.ellipse: whether to show population-specific ellipses
  # show.line: whether to show lines connecting population means with each individual point
  # alpha: the transparency of ellipses
  # index_exclude: the indices of individuals to exclude from the analysis
  #index_include <- setdiff(seq_along(ind_label), index_exclude)
  m <- as.matrix(cov_matrix) 
  #m[is.na(m)]<- median(m, na.rm = T)
  #m<-m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
  e <- eigen(m)
  e_value<-e$values
  x_variance<-e_value[x_axis]/sum(e_value)*100
  y_variance<-e_value[y_axis]/sum(e_value)*100
  e <- as.data.frame(e$vectors)
  e <- cbind(AllStreamsNames, e) ## with the above individuals removed
  e$Population <- factor(e$Population, levels = c("Ross Creek", "Woodworth", "Black Hole", "Church Vault", "Saunders", "Robinson", "Sheep Shearer", "Healeys", "Poole"))
  e$geology <- factor(e$geology, levels = c("Scoured Glacial Till", "Thick Stony Glacial Till", "Silt"))
  #Below is taking the dimensions of data frame e and pasting new column names to indicate PC1, PC2 up to 21.
  colnames(e)[4:(dim(e)[1])]<-paste0("PC",1:(dim(e)[1]-3)) ## make new column names PC1, PC2 etc replacing X1,X2 and so on after 4 because this is where the PCs start and minus 3 
  #colnames(e)[1:2]<-c("individual", "population") #This would change the name of column 1 and 2 to individual and population. 
  assign("pca_table", e, .GlobalEnv)
  
  
  PCA_plot<-ggplot(data=e[,],aes(x=e[,x_axis +3], y=e[,y_axis +3], fill=Population, label=Population, shape=geology)) + #Add 3 because column 1 and 2 is population and individual ID so PC1 and PC2 are actually columns 3 and 4
    geom_point(size=5, alpha=0.9)+
    scale_shape_manual(values = c(23, 24, 21)) +
    #scale_colour_brewer(type="qual") + #was trying to get a different colour scheme to work
    guides(fill = guide_legend(override.aes = list(shape = 22)),
           shape = guide_legend(override.aes = list(fill = "black"))) +#these two lines inside 'guides' are some kind of magic that fixed my legend issues when using shapes that have a fill and border
    labs(fill = 'Population', shape = 'Geology') + #title = "Global SNP Calling with SamTools") +
    geom_hline(yintercept = 0, lty = 2) +
    geom_vline(xintercept = 0, lty = 2) +
    # theme_cowplot() +
    theme(text = element_text(size=23),
          legend.key = element_blank(),
          panel.background = element_blank()) +
    # theme(
    #   axis.text.x = element_blank(),
    #   axis.text.y = element_blank()
    # ) +
    xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
    ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) 
  print(PCA_plot)
} 

PCA1 <- PCA(cov_matrix = AllStreamsSamTools.cov, x_axis = 1, y_axis = 2) #where x_axis 1 and y_axis 2 says plot PC3 and PC4.
#to make it an object for making a panel plot with LD pruned PCA.

ggsave("PCA_AllStreams_SamTools_byGeology_April18_2024.png", path = "C:/Users/cneme/Documents/PCA_LDHeatmaps", bg = "transparent", width = 12, height = 8, units = c("in"), dpi = 300)

ggsave("PCA_AllStreams_SamTools_byGeology_April18_2024.pdf", path = "C:/Users/cneme/Documents/PCA_LDHeatmaps", bg = "transparent", width = 12, height = 8, units = c("in"), dpi = 300)



##PCA global SNPs####
#Data

AllStreamsSamTools.cov <- as.matrix(read.table(paste0("C:/Users/cneme/Documents/PCAs/AllStreams_SamTools_GL.covMat"), header= F))

#I need to bring in data so I can have a population column and individual ID

#Bring in all the sample merge texts from compute canada and merge those to start

BH.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/BlackHole_samplemerge.txt", header = F)
CV.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/ChurchVault_samplemerge.txt", header = F)
HE.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/Healeys_samplemerge.txt", header = F)
PL.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/Poole_samplemerge.txt", header = F)
RB.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/Robinson_samplemerge.txt", header = F)
RC.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/RossCreek_samplemerge.txt", header = F)
SB.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/SaundersBrookDownstream_samplemerge.txt", header = F)
SS.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/SheepShearer_samplemerge.txt", header = F)
WW.names <- read.table("C:/Users/cneme/Documents/PCA_LDheatmaps/WoodworthDownstream_samplemerge.txt", header = F)


#Add a column to each sample table to specify the population or stream name
BH.names$Population <- "Black Hole"
CV.names$Population <- "Church Vault"
HE.names$Population <- "Healeys"
PL.names$Population <- "Poole"
RB.names$Population <- "Robinson"
RC.names$Population <- "Ross Creek"
SB.names$Population <- "Saunders"
SS.names$Population <- "Sheep Shearer"
WW.names$Population <- "Woodworth"

#Add a column for geology
BH.names$geology <- "Scoured Glacial Till"
CV.names$geology <- "Thick Stony Glacial Till"
HE.names$geology <- "Silt"
PL.names$geology <- "Silt"
RB.names$geology <- "Thick Stony Glacial Till"
RC.names$geology <- "Scoured Glacial Till"
SB.names$geology <- "Thick Stony Glacial Till"
SS.names$geology <- "Silt"
WW.names$geology <- "Scoured Glacial Till"

#bind all tables
AllStreamsNames <- rbind(BH.names,CV.names,HE.names,PL.names,RB.names,RC.names,SB.names,SS.names,WW.names)


#change geology column to factor
AllStreamsNames$Population <- as.factor(AllStreamsNames$Population)
AllStreamsNames$geology <- as.factor(AllStreamsNames$geology)

PCA <- function(cov_matrix, x_axis, y_axis)
{
  ## This function takes a covariance matrix and performs PCA. 
  # cov_matrix: a square covariance matrix generated by most pca softwares
  # ind_label: a vector in the same order and length as cov_matrix; it contains the individual labels of the individuals represented in the covariance matrix
  # pop_label: a vector in the same order and length as cov_matrix; it contains the population labels of the individuals represented in the covariance matrix
  # x_axis: an integer that determines which principal component to plot on the x axis
  # y_axis: an integer that determines which principal component to plot on the y axis
  # show.point: whether to show individual points
  # show.label: whether to show population labels
  # show.ellipse: whether to show population-specific ellipses
  # show.line: whether to show lines connecting population means with each individual point
  # alpha: the transparency of ellipses
  # index_exclude: the indices of individuals to exclude from the analysis
  #index_include <- setdiff(seq_along(ind_label), index_exclude)
  m <- as.matrix(cov_matrix) 
  #m[is.na(m)]<- median(m, na.rm = T)
  #m<-m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
  e <- eigen(m)
  e_value<-e$values
  x_variance<-e_value[x_axis]/sum(e_value)*100
  y_variance<-e_value[y_axis]/sum(e_value)*100
  e <- as.data.frame(e$vectors)
  e <- cbind(AllStreamsNames, e) ## with the above individuals removed
  e$Population <- factor(e$Population, levels = c("Ross Creek", "Woodworth", "Black Hole", "Church Vault", "Saunders", "Robinson", "Sheep Shearer", "Healeys", "Poole"))
  e$geology <- factor(e$geology, levels = c("Scoured Glacial Till", "Thick Stony Glacial Till", "Silt"))
  #Below is taking the dimensions of data frame e and pasting new column names to indicate PC1, PC2 up to 21.
  colnames(e)[4:(dim(e)[1])]<-paste0("PC",1:(dim(e)[1]-3)) ## make new column names PC1, PC2 etc replacing X1,X2 and so on after 4 because this is where the PCs start and minus 3 
  #colnames(e)[1:2]<-c("individual", "population") #This would change the name of column 1 and 2 to individual and population. 
  assign("pca_table", e, .GlobalEnv)
  
  
  PCA_plot<-ggplot(data=e[,],aes(x=e[,x_axis +3], y=e[,y_axis +3], fill=Population, label=Population, shape=geology)) + #Add 3 because column 1 and 2 is population and individual ID so PC1 and PC2 are actually columns 3 and 4
    geom_point(size=5, alpha=0.9)+
    scale_shape_manual(values = c(23, 24, 21)) +
    #scale_colour_brewer(type="qual") + #was trying to get a different colour scheme to work
    guides(fill = guide_legend(override.aes = list(shape = 22)),
           shape = guide_legend(override.aes = list(fill = "black"))) +#these two lines inside 'guides' are some kind of magic that fixed my legend issues when using shapes that have a fill and border
    labs(fill = 'Population', shape = 'Geology') + #title = "Global SNP Calling with SamTools") +
    geom_hline(yintercept = 0, lty = 2) +
    geom_vline(xintercept = 0, lty = 2) +
    # theme_cowplot() +
    theme(text = element_text(size=23),
          legend.key = element_blank(),
          panel.background = element_blank()) +
    # theme(
    #   axis.text.x = element_blank(),
    #   axis.text.y = element_blank()
    # ) +
    xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
    ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) 
  print(PCA_plot)
} 

PCA1 <- PCA(cov_matrix = AllStreamsSamTools.cov, x_axis = 1, y_axis = 2) #where x_axis 1 and y_axis 2 says plot PC3 and PC4.
#to make it an object for making a panel plot with LD pruned PCA.